server:
  error:
    include-message: always

spring:
  appplication:
    name: SpectraSports
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false

spectra-sports:
  email:
    api-key: ${SENDINBLUE_API_KEY}
  domain: http:localhost:8080
  s3-access-key: ${S3_ACCESS_KEY}
  s3-secret-key: ${S3_SECRET_KEY}
  s3-bucket-name: ${S3_BUCKET_NAME}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
