package com.spectra.sports.constant;

public final class SpectraConstant {
    public static final String SPECTRA_SPORTS = "Spectra Sports";
    public static final String SPECTRA_SPORTS_EMAIL = "spectrasports@example.com";
    public static final String SUNDAY = "Sun";
    public static final String MONDAY = "Mon";
    public static final String TUESDAY = "Tue";
    public static final String WEDNESDAY = "Wed";
    public static final String THURSDAY = "Thu";
    public static final String FRIDAY = "Fri";
    public static final String SATURDAY = "Sat";
    public static final String SENDER = "sender";
    public static final String TO = "to";
    public static final String NAME = "name";
    public static final String EMAIL = "email";
    public static final String SUBJECT = "subject";
    public static final String HTML_CONTENT = "htmlContent";
    public static final String DOMAIN = "DOMAIN";
    public static final String USERNAME = "username";
    public static final String PASSWORD = "password";
    public static final String STUDENT_ID = "studentId";
    public static final String MENTOR_ID = "mentorId";
    public static final String MENTOR_TYPE = "mentorType";
    public static final String ACADEMY_TYPE = "academyType";
    public static final String ACADEMY_NAME = "academyName";
    public static final String ACADEMY_ID = "academyId";
    public static final String BODY = "body";
    public static final String STATUS = "status";
    public static final String ERROR = "error";
    public static final String MESSAGE = "message";
    public static final String MAPPED_NAME = "mappedName";
    public static final String USER = "user";
    public static final String USER_ID = "userId";
    public static final String ACCESS_TOKEN = "accessToken";
    public static final String STUDENT_MENTOR = "studentMentor";
    public static final String STUDENT_MENTOR_ACADEMY = "studentMentorAcademy";
    public static final String FLAG = "flag";
    public static final String ACADEMY = "academy";
    public static final String MENTOR = "mentor";
    public static final String SEND_IN_BLUE_URL = "https://api.sendinblue.com/v3/smtp/email";
    public static final String OTP = "otp";
    public static final String MONTHS = "months";
    public static final String PLAN = "plan";
    public static final String SLOT = "slot";
    public static final String SLOT_DAYS = "slotDays";
    public static final String AMOUNT = "amount";
}
